name: Main Workflow

on: [push]

jobs:
  call-reusable-workflow:
    runs-on: ubuntu-latest
    env:
      PARAM: value
    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/reusable.yml
        with:
          my_param: ${{ env.PARAM }}