name: Python package
on:
  push:
    branches: ["*"]
env:
  MY_PARAMETER: 'a value'
jobs:
  start-reusable-job:
    uses: ./.github/workflows/run-test.yaml
    with:
      my_parameter: ${{env.MY_PARAMETER}}
  next-job:
    runs-on: ubuntu-latest
    needs: start-reusable-job
    steps:
    - name: test
      run: |
        echo "it works!"
